/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlgorithmResetButton: typeof import('./src/components/algorithm/AlgorithmResetButton.vue')['default']
    AlgorithmResetModal: typeof import('./src/components/algorithm/AlgorithmResetModal.vue')['default']
    ConceptVideosDesktopTable: typeof import('./src/components/desktop/ConceptVideosDesktopTable.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FavoritesDesktopTable: typeof import('./src/components/desktop/FavoritesDesktopTable.vue')['default']
    H5BackLink: typeof import('./src/components/H5BackLink.vue')['default']
    HistoryDesktopTable: typeof import('./src/components/desktop/HistoryDesktopTable.vue')['default']
    HomeImmersivePlayerOverlay: typeof import('./src/components/home/HomeImmersivePlayerOverlay.vue')['default']
    LearningPathDetailItemsDesktopTable: typeof import('./src/components/desktop/LearningPathDetailItemsDesktopTable.vue')['default']
    LearningPathListDesktopTable: typeof import('./src/components/desktop/LearningPathListDesktopTable.vue')['default']
    MobileTabBar: typeof import('./src/components/MobileTabBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultsDesktopTable: typeof import('./src/components/desktop/SearchResultsDesktopTable.vue')['default']
    TurnstileWidget: typeof import('./src/components/TurnstileWidget.vue')['default']
    VideoCommentsDesktopTable: typeof import('./src/components/desktop/VideoCommentsDesktopTable.vue')['default']
    VideoListDesktopTable: typeof import('./src/components/desktop/VideoListDesktopTable.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
