"""管理员管理接口 ``AppError.code`` 常量。"""

ADMIN_USER_NOT_FOUND = "ADMIN_USER_NOT_FOUND"
ADMIN_CANNOT_DISABLE_SELF = "ADMIN_CANNOT_DISABLE_SELF"
ADMIN_CANNOT_DISABLE_LAST_ACTIVE_ADMIN = "ADMIN_CANNOT_DISABLE_LAST_ACTIVE_ADMIN"
