"""评论模块 ``AppError.code`` 常量（机器可读）。"""

COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND"
COMMENT_FORBIDDEN = "COMMENT_FORBIDDEN"
COMMENT_VIDEO_NOT_PUBLISHED = "COMMENT_VIDEO_NOT_PUBLISHED"
COMMENT_RATE_LIMITED = "COMMENT_RATE_LIMITED"
COMMENT_RATE_LIMIT_BACKEND_UNAVAILABLE = "COMMENT_RATE_LIMIT_BACKEND_UNAVAILABLE"
