"""视频互动（点赞/收藏）``AppError.code`` 常量。"""

VIDEO_INTERACTION_REQUIRES_PUBLISHED = "VIDEO_INTERACTION_REQUIRES_PUBLISHED"
VIDEO_LIKE_ALREADY_EXISTS = "VIDEO_LIKE_ALREADY_EXISTS"
VIDEO_LIKE_NOT_FOUND = "VIDEO_LIKE_NOT_FOUND"
VIDEO_FAVORITE_ALREADY_EXISTS = "VIDEO_FAVORITE_ALREADY_EXISTS"
VIDEO_FAVORITE_NOT_FOUND = "VIDEO_FAVORITE_NOT_FOUND"
