"""视频模块 `AppError.code` 常量（机器可读）。"""

VIDEO_TAG_NOT_FOUND = "VIDEO_TAG_NOT_FOUND"
VIDEO_CATEGORY_NOT_FOUND = "VIDEO_CATEGORY_NOT_FOUND"
VIDEO_CREATE_FAILED = "VIDEO_CREATE_FAILED"
VIDEO_NOT_FOUND = "VIDEO_NOT_FOUND"
VIDEO_DELETE_FORBIDDEN = "VIDEO_DELETE_FORBIDDEN"
VIDEO_STATUS_QUERY_FORBIDDEN = "VIDEO_STATUS_QUERY_FORBIDDEN"
VIDEO_EDIT_FORBIDDEN = "VIDEO_EDIT_FORBIDDEN"
VIDEO_STATUS_TRANSITION_INVALID = "VIDEO_STATUS_TRANSITION_INVALID"

VIDEO_LIST_CURSOR_OFFSET_CONFLICT = "VIDEO_LIST_CURSOR_OFFSET_CONFLICT"
VIDEO_LIST_CURSOR_WITHOUT_LIMIT = "VIDEO_LIST_CURSOR_WITHOUT_LIMIT"
VIDEO_LIST_INVALID_CURSOR = "VIDEO_LIST_INVALID_CURSOR"
VIDEO_LIST_FOLLOW_FEED_REQUIRES_AUTH = "VIDEO_LIST_FOLLOW_FEED_REQUIRES_AUTH"

VIDEO_IDEMPOTENCY_CONFLICT = "VIDEO_IDEMPOTENCY_CONFLICT"
VIDEO_IDEMPOTENCY_BACKEND_UNAVAILABLE = "VIDEO_IDEMPOTENCY_BACKEND_UNAVAILABLE"

# --- 阶段 8.2：审核与状态流转 ---
VIDEO_PATCH_STATUS_USE_DEDICATED_ENDPOINT = "VIDEO_PATCH_STATUS_USE_DEDICATED_ENDPOINT"
VIDEO_PATCH_ADMIN_OFFLINE_USE_ENDPOINT = "VIDEO_PATCH_ADMIN_OFFLINE_USE_ENDPOINT"
VIDEO_SUBMIT_FORBIDDEN = "VIDEO_SUBMIT_FORBIDDEN"
VIDEO_SUBMIT_INVALID_STATE = "VIDEO_SUBMIT_INVALID_STATE"
VIDEO_APPROVE_FORBIDDEN = "VIDEO_APPROVE_FORBIDDEN"
VIDEO_APPROVE_INVALID_STATE = "VIDEO_APPROVE_INVALID_STATE"
VIDEO_REJECT_FORBIDDEN = "VIDEO_REJECT_FORBIDDEN"
VIDEO_REJECT_INVALID_STATE = "VIDEO_REJECT_INVALID_STATE"
VIDEO_OFFLINE_FORBIDDEN = "VIDEO_OFFLINE_FORBIDDEN"
VIDEO_OFFLINE_INVALID_STATE = "VIDEO_OFFLINE_INVALID_STATE"

VIDEO_CONFLICT_OPTIMISTIC = "VIDEO_CONFLICT_OPTIMISTIC"

# 工作流审计只读列表：非管理员且非作者
VIDEO_WORKFLOW_EVENTS_FORBIDDEN = "VIDEO_WORKFLOW_EVENTS_FORBIDDEN"

# --- 阶段 11.2：VOD 媒资绑定 ---
VIDEO_VOD_ID_CREATE_FORBIDDEN = "VIDEO_VOD_ID_CREATE_FORBIDDEN"
VIDEO_VOD_ID_CONFLICT = "VIDEO_VOD_ID_CONFLICT"
VIDEO_VOD_ALREADY_BOUND = "VIDEO_VOD_ALREADY_BOUND"
VIDEO_VOD_FIELDS_PATCH_FORBIDDEN = "VIDEO_VOD_FIELDS_PATCH_FORBIDDEN"
VIDEO_BIND_VOD_FORBIDDEN = "VIDEO_BIND_VOD_FORBIDDEN"

# --- 阶段 11.3：VOD 播放凭证 ---
VIDEO_PLAY_OFFLINE_FORBIDDEN = "VIDEO_PLAY_OFFLINE_FORBIDDEN"
VIDEO_PLAY_VOD_NOT_BOUND = "VIDEO_PLAY_VOD_NOT_BOUND"
VIDEO_PLAY_NO_MEDIA = "VIDEO_PLAY_NO_MEDIA"

# --- 本机成片上传与流式播放 ---
VIDEO_LOCAL_UPLOAD_FORBIDDEN = "VIDEO_LOCAL_UPLOAD_FORBIDDEN"
VIDEO_LOCAL_BAD_EXTENSION = "VIDEO_LOCAL_BAD_EXTENSION"
VIDEO_LOCAL_TOO_LARGE = "VIDEO_LOCAL_TOO_LARGE"
VIDEO_LOCAL_STREAM_TOKEN_INVALID = "VIDEO_LOCAL_STREAM_TOKEN_INVALID"
VIDEO_LOCAL_FILE_MISSING = "VIDEO_LOCAL_FILE_MISSING"
VIDEO_LOCAL_PATH_INVALID = "VIDEO_LOCAL_PATH_INVALID"
VIDEO_LOCAL_NOT_READY = "VIDEO_LOCAL_NOT_READY"

# --- 阶段 13：搜索与发现 ---
VIDEO_SEARCH_INVALID_SORT = "VIDEO_SEARCH_INVALID_SORT"
VIDEO_SEARCH_KEYWORD_TOO_LONG = "VIDEO_SEARCH_KEYWORD_TOO_LONG"
VIDEO_SEARCH_RATE_LIMITED = "VIDEO_SEARCH_RATE_LIMITED"

# --- 稿件附属文件 ---
VIDEO_ATTACHMENT_FORBIDDEN = "VIDEO_ATTACHMENT_FORBIDDEN"
VIDEO_ATTACHMENT_NOT_FOUND = "VIDEO_ATTACHMENT_NOT_FOUND"
VIDEO_ATTACHMENT_TOO_MANY = "VIDEO_ATTACHMENT_TOO_MANY"
