"""播放记录 ``AppError.code`` 常量。"""

VIEW_RECORD_REQUIRES_PUBLISHED = "VIEW_RECORD_REQUIRES_PUBLISHED"
VIEW_RECORD_CONFLICT = "VIEW_RECORD_CONFLICT"
VIEW_RECORD_LAST_VIEWED_IN_FUTURE = "VIEW_RECORD_LAST_VIEWED_IN_FUTURE"
VIEW_RECORD_CURSOR_WITH_OFFSET = "VIEW_RECORD_CURSOR_WITH_OFFSET"
VIEW_RECORD_CURSOR_INVALID = "VIEW_RECORD_CURSOR_INVALID"
