"""VOD 上传相关 ``AppError.code``。"""

VOD_CONFIG_INCOMPLETE = "VOD_CONFIG_INCOMPLETE"
VOD_SDK_NOT_INSTALLED = "VOD_SDK_NOT_INSTALLED"
VOD_API_ERROR = "VOD_API_ERROR"
VOD_FILENAME_INVALID = "VOD_FILENAME_INVALID"
VOD_REFRESH_UPLOAD_FORBIDDEN = "VOD_REFRESH_UPLOAD_FORBIDDEN"
VOD_REFRESH_UPLOAD_RATE_LIMITED = "VOD_REFRESH_UPLOAD_RATE_LIMITED"

# --- 阶段 11.4：VOD HTTP 回调 ---
VOD_CALLBACK_NOT_CONFIGURED = "VOD_CALLBACK_NOT_CONFIGURED"
VOD_CALLBACK_UNAUTHORIZED = "VOD_CALLBACK_UNAUTHORIZED"
VOD_CALLBACK_INVALID_JSON = "VOD_CALLBACK_INVALID_JSON"
VOD_CALLBACK_VIDEO_ID_MISSING = "VOD_CALLBACK_VIDEO_ID_MISSING"
VOD_CALLBACK_VIDEO_NOT_FOUND = "VOD_CALLBACK_VIDEO_NOT_FOUND"
